# Generated by Django 5.2.17 on 2026-09-28 03:50

import diagnosis.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result_image",
                    models.ImageField(upload_to=diagnosis.models.result_path),
                ),
                ("caries_count", models.PositiveIntegerField(default=0)),
                ("filling_count", models.PositiveIntegerField(default=0)),
                ("detections", models.JSONField(default=list)),
                ("clahe_models", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
